/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package info.exascale.daoc;

public class ClusterOptions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ClusterOptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ClusterOptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        daocJNI.delete_ClusterOptions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setGamma(float value) {
    daocJNI.ClusterOptions_gamma_set(swigCPtr, this, value);
  }

  public float getGamma() {
    return daocJNI.ClusterOptions_gamma_get(swigCPtr, this);
  }

  public void setFilterMarg(float value) {
    daocJNI.ClusterOptions_filterMarg_set(swigCPtr, this, value);
  }

  public float getFilterMarg() {
    return daocJNI.ClusterOptions_filterMarg_get(swigCPtr, this);
  }

  public void setValidation(SWIGTYPE_p_Validation value) {
    daocJNI.ClusterOptions_validation_set(swigCPtr, this, SWIGTYPE_p_Validation.getCPtr(value));
  }

  public SWIGTYPE_p_Validation getValidation() {
    return new SWIGTYPE_p_Validation(daocJNI.ClusterOptions_validation_get(swigCPtr, this), true);
  }

  public void setRootMax(int value) {
    daocJNI.ClusterOptions_rootMax_set(swigCPtr, this, value);
  }

  public int getRootMax() {
    return daocJNI.ClusterOptions_rootMax_get(swigCPtr, this);
  }

  public void setSpeedup(SWIGTYPE_p_Speedup value) {
    daocJNI.ClusterOptions_speedup_set(swigCPtr, this, SWIGTYPE_p_Speedup.getCPtr(value));
  }

  public SWIGTYPE_p_Speedup getSpeedup() {
    return new SWIGTYPE_p_Speedup(daocJNI.ClusterOptions_speedup_get(swigCPtr, this), true);
  }

  public void setGainMarg(float value) {
    daocJNI.ClusterOptions_gainMarg_set(swigCPtr, this, value);
  }

  public float getGainMarg() {
    return daocJNI.ClusterOptions_gainMarg_get(swigCPtr, this);
  }

  public void setModtrace(boolean value) {
    daocJNI.ClusterOptions_modtrace_set(swigCPtr, this, value);
  }

  public boolean getModtrace() {
    return daocJNI.ClusterOptions_modtrace_get(swigCPtr, this);
  }

  public ClusterOptions() {
    this(daocJNI.new_ClusterOptions(), true);
  }

}
