/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package info.exascale.daoc;

public class CnlParser {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CnlParser(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CnlParser obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        daocJNI.delete_CnlParser(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CnlParser(SWIGTYPE_p_string filename) {
    this(daocJNI.new_CnlParser(SWIGTYPE_p_string.getCPtr(filename)), true);
  }

  public boolean fuzzy() {
    return daocJNI.CnlParser_fuzzy(swigCPtr, this);
  }

  public SWIGTYPE_p_shared_ptrT_daoc__RawMembershipT_std__vectorT_daoc__SimpleLinkT_float_t_t_t_t sbuild(SWIGTYPE_p_daoc__IdItemsT_daoc__NodeT_std__vectorT_daoc__SimpleLinkT_float_t_t_t_t idnodes) {
    return new SWIGTYPE_p_shared_ptrT_daoc__RawMembershipT_std__vectorT_daoc__SimpleLinkT_float_t_t_t_t(daocJNI.CnlParser_sbuild(swigCPtr, this, SWIGTYPE_p_daoc__IdItemsT_daoc__NodeT_std__vectorT_daoc__SimpleLinkT_float_t_t_t_t.getCPtr(idnodes)), true);
  }

  public SWIGTYPE_p_shared_ptrT_daoc__RawMembershipT_std__vectorT_daoc__WeightedLinkT_float_t_t_t_t build(SWIGTYPE_p_daoc__IdItemsT_daoc__NodeT_std__vectorT_daoc__WeightedLinkT_float_t_t_t_t idnodes) {
    return new SWIGTYPE_p_shared_ptrT_daoc__RawMembershipT_std__vectorT_daoc__WeightedLinkT_float_t_t_t_t(daocJNI.CnlParser_build(swigCPtr, this, SWIGTYPE_p_daoc__IdItemsT_daoc__NodeT_std__vectorT_daoc__WeightedLinkT_float_t_t_t_t.getCPtr(idnodes)), true);
  }

}
