/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package info.exascale.daoc;

public class daoc {
  public static void setFtrace(SWIGTYPE_p_FILE value) {
    daocJNI.ftrace_set(SWIGTYPE_p_FILE.getCPtr(value));
  }

  public static SWIGTYPE_p_FILE getFtrace() {
    long cPtr = daocJNI.ftrace_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_FILE(cPtr, false);
  }

  public static double getACCWEIGHT_NONE() {
    return daocJNI.ACCWEIGHT_NONE_get();
  }

  public static double getGAIN_NONE() {
    return daocJNI.GAIN_NONE_get();
  }

  public static long getID_NONE() {
    return daocJNI.ID_NONE_get();
  }

  public static long getID_MAX() {
    return daocJNI.ID_MAX_get();
  }

  public static int getCOUPLING_NONE() {
    return daocJNI.COUPLING_NONE_get();
  }

  public static int getCOUPLING_MAX() {
    return daocJNI.COUPLING_MAX_get();
  }

  public static long getLEVEL_NONE() {
    return daocJNI.LEVEL_NONE_get();
  }

  public static long getLEVEL_MAX() {
    return daocJNI.LEVEL_MAX_get();
  }

  public static SWIGTYPE_p_string pad(SWIGTYPE_p_string str, short maxpad, char symb, boolean left) {
    return new SWIGTYPE_p_string(daocJNI.pad__SWIG_0(SWIGTYPE_p_string.getCPtr(str), maxpad, symb, left), false);
  }

  public static SWIGTYPE_p_string pad(SWIGTYPE_p_string str, short maxpad, char symb) {
    return new SWIGTYPE_p_string(daocJNI.pad__SWIG_1(SWIGTYPE_p_string.getCPtr(str), maxpad, symb), false);
  }

  public static SWIGTYPE_p_string pad(SWIGTYPE_p_string str, short maxpad) {
    return new SWIGTYPE_p_string(daocJNI.pad__SWIG_2(SWIGTYPE_p_string.getCPtr(str), maxpad), false);
  }

  public static SWIGTYPE_p_shared_ptrT_daoc__HierarchyT_std__vectorT_daoc__SimpleLinkT_float_t_t_t_t scluster(SWIGTYPE_p_daoc__NodesT_std__vectorT_daoc__SimpleLinkT_float_t_t_t nodes, boolean edges, ClusterOptions opts) {
    return new SWIGTYPE_p_shared_ptrT_daoc__HierarchyT_std__vectorT_daoc__SimpleLinkT_float_t_t_t_t(daocJNI.scluster__SWIG_0(SWIGTYPE_p_daoc__NodesT_std__vectorT_daoc__SimpleLinkT_float_t_t_t.getCPtr(nodes), edges, ClusterOptions.getCPtr(opts), opts), true);
  }

  public static SWIGTYPE_p_shared_ptrT_daoc__HierarchyT_std__vectorT_daoc__SimpleLinkT_float_t_t_t_t scluster(SWIGTYPE_p_daoc__NodesT_std__vectorT_daoc__SimpleLinkT_float_t_t_t nodes, boolean edges) {
    return new SWIGTYPE_p_shared_ptrT_daoc__HierarchyT_std__vectorT_daoc__SimpleLinkT_float_t_t_t_t(daocJNI.scluster__SWIG_1(SWIGTYPE_p_daoc__NodesT_std__vectorT_daoc__SimpleLinkT_float_t_t_t.getCPtr(nodes), edges), true);
  }

  public static SWIGTYPE_p_shared_ptrT_daoc__HierarchyT_std__vectorT_daoc__WeightedLinkT_float_t_t_t_t cluster(SWIGTYPE_p_daoc__NodesT_std__vectorT_daoc__WeightedLinkT_float_t_t_t nodes, boolean edges, ClusterOptions opts) {
    return new SWIGTYPE_p_shared_ptrT_daoc__HierarchyT_std__vectorT_daoc__WeightedLinkT_float_t_t_t_t(daocJNI.cluster__SWIG_0(SWIGTYPE_p_daoc__NodesT_std__vectorT_daoc__WeightedLinkT_float_t_t_t.getCPtr(nodes), edges, ClusterOptions.getCPtr(opts), opts), true);
  }

  public static SWIGTYPE_p_shared_ptrT_daoc__HierarchyT_std__vectorT_daoc__WeightedLinkT_float_t_t_t_t cluster(SWIGTYPE_p_daoc__NodesT_std__vectorT_daoc__WeightedLinkT_float_t_t_t nodes, boolean edges) {
    return new SWIGTYPE_p_shared_ptrT_daoc__HierarchyT_std__vectorT_daoc__WeightedLinkT_float_t_t_t_t(daocJNI.cluster__SWIG_1(SWIGTYPE_p_daoc__NodesT_std__vectorT_daoc__WeightedLinkT_float_t_t_t.getCPtr(nodes), edges), true);
  }

  public static void intrinsicMeasuresSArcs(Intrinsics ins, SWIGTYPE_p_daoc__ClustersT_std__vectorT_daoc__SimpleLinkT_float_t_t_t cls, double weight, double gamma) {
    daocJNI.intrinsicMeasuresSArcs__SWIG_0(Intrinsics.getCPtr(ins), ins, SWIGTYPE_p_daoc__ClustersT_std__vectorT_daoc__SimpleLinkT_float_t_t_t.getCPtr(cls), weight, gamma);
  }

  public static void intrinsicMeasuresSArcs(Intrinsics ins, SWIGTYPE_p_daoc__ClustersT_std__vectorT_daoc__SimpleLinkT_float_t_t_t cls, double weight) {
    daocJNI.intrinsicMeasuresSArcs__SWIG_1(Intrinsics.getCPtr(ins), ins, SWIGTYPE_p_daoc__ClustersT_std__vectorT_daoc__SimpleLinkT_float_t_t_t.getCPtr(cls), weight);
  }

  public static void intrinsicMeasuresArcs(Intrinsics ins, SWIGTYPE_p_daoc__ClustersT_std__vectorT_daoc__WeightedLinkT_float_t_t_t cls, double weight, double gamma) {
    daocJNI.intrinsicMeasuresArcs__SWIG_0(Intrinsics.getCPtr(ins), ins, SWIGTYPE_p_daoc__ClustersT_std__vectorT_daoc__WeightedLinkT_float_t_t_t.getCPtr(cls), weight, gamma);
  }

  public static void intrinsicMeasuresArcs(Intrinsics ins, SWIGTYPE_p_daoc__ClustersT_std__vectorT_daoc__WeightedLinkT_float_t_t_t cls, double weight) {
    daocJNI.intrinsicMeasuresArcs__SWIG_1(Intrinsics.getCPtr(ins), ins, SWIGTYPE_p_daoc__ClustersT_std__vectorT_daoc__WeightedLinkT_float_t_t_t.getCPtr(cls), weight);
  }

  public static void intrinsicMeasuresSEdges(Intrinsics ins, SWIGTYPE_p_daoc__ClustersT_std__vectorT_daoc__SimpleLinkT_float_t_t_t cls, double weight, double gamma) {
    daocJNI.intrinsicMeasuresSEdges__SWIG_0(Intrinsics.getCPtr(ins), ins, SWIGTYPE_p_daoc__ClustersT_std__vectorT_daoc__SimpleLinkT_float_t_t_t.getCPtr(cls), weight, gamma);
  }

  public static void intrinsicMeasuresSEdges(Intrinsics ins, SWIGTYPE_p_daoc__ClustersT_std__vectorT_daoc__SimpleLinkT_float_t_t_t cls, double weight) {
    daocJNI.intrinsicMeasuresSEdges__SWIG_1(Intrinsics.getCPtr(ins), ins, SWIGTYPE_p_daoc__ClustersT_std__vectorT_daoc__SimpleLinkT_float_t_t_t.getCPtr(cls), weight);
  }

  public static void intrinsicMeasuresEdges(Intrinsics ins, SWIGTYPE_p_daoc__ClustersT_std__vectorT_daoc__WeightedLinkT_float_t_t_t cls, double weight, double gamma) {
    daocJNI.intrinsicMeasuresEdges__SWIG_0(Intrinsics.getCPtr(ins), ins, SWIGTYPE_p_daoc__ClustersT_std__vectorT_daoc__WeightedLinkT_float_t_t_t.getCPtr(cls), weight, gamma);
  }

  public static void intrinsicMeasuresEdges(Intrinsics ins, SWIGTYPE_p_daoc__ClustersT_std__vectorT_daoc__WeightedLinkT_float_t_t_t cls, double weight) {
    daocJNI.intrinsicMeasuresEdges__SWIG_1(Intrinsics.getCPtr(ins), ins, SWIGTYPE_p_daoc__ClustersT_std__vectorT_daoc__WeightedLinkT_float_t_t_t.getCPtr(cls), weight);
  }

  public static double sloadClusters(SWIGTYPE_p_daoc__ClustersT_daoc__LinksT_daoc__LinkT_daoc__LinkWeight_false_t_t_t clusters, SGraphPtr graph, SWIGTYPE_p_string filename, SWIGTYPE_p_Validation validation) {
    return daocJNI.sloadClusters__SWIG_0(SWIGTYPE_p_daoc__ClustersT_daoc__LinksT_daoc__LinkT_daoc__LinkWeight_false_t_t_t.getCPtr(clusters), SGraphPtr.getCPtr(graph), graph, SWIGTYPE_p_string.getCPtr(filename), SWIGTYPE_p_Validation.getCPtr(validation));
  }

  public static double sloadClusters(SWIGTYPE_p_daoc__ClustersT_daoc__LinksT_daoc__LinkT_daoc__LinkWeight_false_t_t_t clusters, SGraphPtr graph, SWIGTYPE_p_string filename) {
    return daocJNI.sloadClusters__SWIG_1(SWIGTYPE_p_daoc__ClustersT_daoc__LinksT_daoc__LinkT_daoc__LinkWeight_false_t_t_t.getCPtr(clusters), SGraphPtr.getCPtr(graph), graph, SWIGTYPE_p_string.getCPtr(filename));
  }

  public static double loadClusters(SWIGTYPE_p_daoc__ClustersT_daoc__LinksT_daoc__LinkT_daoc__LinkWeight_true_t_t_t clusters, GraphPtr graph, SWIGTYPE_p_string filename, SWIGTYPE_p_Validation validation) {
    return daocJNI.loadClusters__SWIG_0(SWIGTYPE_p_daoc__ClustersT_daoc__LinksT_daoc__LinkT_daoc__LinkWeight_true_t_t_t.getCPtr(clusters), GraphPtr.getCPtr(graph), graph, SWIGTYPE_p_string.getCPtr(filename), SWIGTYPE_p_Validation.getCPtr(validation));
  }

  public static double loadClusters(SWIGTYPE_p_daoc__ClustersT_daoc__LinksT_daoc__LinkT_daoc__LinkWeight_true_t_t_t clusters, GraphPtr graph, SWIGTYPE_p_string filename) {
    return daocJNI.loadClusters__SWIG_1(SWIGTYPE_p_daoc__ClustersT_daoc__LinksT_daoc__LinkT_daoc__LinkWeight_true_t_t_t.getCPtr(clusters), GraphPtr.getCPtr(graph), graph, SWIGTYPE_p_string.getCPtr(filename));
  }

  public static SWIGTYPE_p_daoc__LinksT_daoc__AccLinkT_daoc__LinksT_daoc__SimpleLinkT_daoc__LinkWeight_t_t_t_t__iterator addSCLink(SWIGTYPE_p_daoc__LinksT_daoc__AccLinkT_std__vectorT_daoc__SimpleLinkT_float_t_t_t_t links, SWIGTYPE_p_daoc__LinksT_daoc__AccLinkT_daoc__LinksT_daoc__SimpleLinkT_daoc__LinkWeight_t_t_t_t__iterator bln, SWIGTYPE_p_daoc__ClusterT_std__vectorT_daoc__SimpleLinkT_float_t_t_t dest, double weight) {
    return new SWIGTYPE_p_daoc__LinksT_daoc__AccLinkT_daoc__LinksT_daoc__SimpleLinkT_daoc__LinkWeight_t_t_t_t__iterator(daocJNI.addSCLink(SWIGTYPE_p_daoc__LinksT_daoc__AccLinkT_std__vectorT_daoc__SimpleLinkT_float_t_t_t_t.getCPtr(links), SWIGTYPE_p_daoc__LinksT_daoc__AccLinkT_daoc__LinksT_daoc__SimpleLinkT_daoc__LinkWeight_t_t_t_t__iterator.getCPtr(bln), SWIGTYPE_p_daoc__ClusterT_std__vectorT_daoc__SimpleLinkT_float_t_t_t.getCPtr(dest), weight), true);
  }

  public static SWIGTYPE_p_daoc__LinksT_daoc__AccLinkT_daoc__LinksT_daoc__SimpleLinkT_daoc__LinkWeight_t_t_t_t__iterator addCLink(SWIGTYPE_p_daoc__LinksT_daoc__AccLinkT_std__vectorT_daoc__SimpleLinkT_float_t_t_t_t links, SWIGTYPE_p_daoc__LinksT_daoc__AccLinkT_daoc__LinksT_daoc__SimpleLinkT_daoc__LinkWeight_t_t_t_t__iterator bln, SWIGTYPE_p_daoc__ClusterT_std__vectorT_daoc__SimpleLinkT_float_t_t_t dest, double weight) {
    return new SWIGTYPE_p_daoc__LinksT_daoc__AccLinkT_daoc__LinksT_daoc__SimpleLinkT_daoc__LinkWeight_t_t_t_t__iterator(daocJNI.addCLink(SWIGTYPE_p_daoc__LinksT_daoc__AccLinkT_std__vectorT_daoc__SimpleLinkT_float_t_t_t_t.getCPtr(links), SWIGTYPE_p_daoc__LinksT_daoc__AccLinkT_daoc__LinksT_daoc__SimpleLinkT_daoc__LinkWeight_t_t_t_t__iterator.getCPtr(bln), SWIGTYPE_p_daoc__ClusterT_std__vectorT_daoc__SimpleLinkT_float_t_t_t.getCPtr(dest), weight), true);
  }

  public static void validateSArcs(SWIGTYPE_p_daoc__StoredItemsT_daoc__NodeT_std__vectorT_daoc__SimpleLinkT_float_t_t_t_t nodes, SWIGTYPE_p_double weight, SWIGTYPE_p_unsigned_long_long linksNum, boolean severe) {
    daocJNI.validateSArcs(SWIGTYPE_p_daoc__StoredItemsT_daoc__NodeT_std__vectorT_daoc__SimpleLinkT_float_t_t_t_t.getCPtr(nodes), SWIGTYPE_p_double.getCPtr(weight), SWIGTYPE_p_unsigned_long_long.getCPtr(linksNum), severe);
  }

  public static void validateArcs(SWIGTYPE_p_daoc__StoredItemsT_daoc__NodeT_std__vectorT_daoc__WeightedLinkT_float_t_t_t_t nodes, SWIGTYPE_p_double weight, SWIGTYPE_p_unsigned_long_long linksNum, boolean severe) {
    daocJNI.validateArcs(SWIGTYPE_p_daoc__StoredItemsT_daoc__NodeT_std__vectorT_daoc__WeightedLinkT_float_t_t_t_t.getCPtr(nodes), SWIGTYPE_p_double.getCPtr(weight), SWIGTYPE_p_unsigned_long_long.getCPtr(linksNum), severe);
  }

  public static void validateSEdges(SWIGTYPE_p_daoc__StoredItemsT_daoc__NodeT_std__vectorT_daoc__SimpleLinkT_float_t_t_t_t nodes, SWIGTYPE_p_double weight, SWIGTYPE_p_unsigned_long_long linksNum, boolean severe) {
    daocJNI.validateSEdges(SWIGTYPE_p_daoc__StoredItemsT_daoc__NodeT_std__vectorT_daoc__SimpleLinkT_float_t_t_t_t.getCPtr(nodes), SWIGTYPE_p_double.getCPtr(weight), SWIGTYPE_p_unsigned_long_long.getCPtr(linksNum), severe);
  }

  public static void validateEdges(SWIGTYPE_p_daoc__StoredItemsT_daoc__NodeT_std__vectorT_daoc__WeightedLinkT_float_t_t_t_t nodes, SWIGTYPE_p_double weight, SWIGTYPE_p_unsigned_long_long linksNum, boolean severe) {
    daocJNI.validateEdges(SWIGTYPE_p_daoc__StoredItemsT_daoc__NodeT_std__vectorT_daoc__WeightedLinkT_float_t_t_t_t.getCPtr(nodes), SWIGTYPE_p_double.getCPtr(weight), SWIGTYPE_p_unsigned_long_long.getCPtr(linksNum), severe);
  }

  public static double SNodeArcsWeight(SNode el) {
    return daocJNI.SNodeArcsWeight(SNode.getCPtr(el), el);
  }

  public static double NodeArcsWeight(Node el) {
    return daocJNI.NodeArcsWeight(Node.getCPtr(el), el);
  }

  public static double SNodeEdgesWeight(SNode el) {
    return daocJNI.SNodeEdgesWeight(SNode.getCPtr(el), el);
  }

  public static double NodeEdgesWeight(Node el) {
    return daocJNI.NodeEdgesWeight(Node.getCPtr(el), el);
  }

}
