/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package info.exascale.daoc;

public class HierScore {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected HierScore(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HierScore obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        daocJNI.delete_HierScore(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setModularity(float value) {
    daocJNI.HierScore_modularity_set(swigCPtr, this, value);
  }

  public float getModularity() {
    return daocJNI.HierScore_modularity_get(swigCPtr, this);
  }

  public void setGamma(float value) {
    daocJNI.HierScore_gamma_set(swigCPtr, this, value);
  }

  public float getGamma() {
    return daocJNI.HierScore_gamma_get(swigCPtr, this);
  }

  public void setEgamma(float value) {
    daocJNI.HierScore_egamma_set(swigCPtr, this, value);
  }

  public float getEgamma() {
    return daocJNI.HierScore_egamma_get(swigCPtr, this);
  }

  public void setConductance(float value) {
    daocJNI.HierScore_conductance_set(swigCPtr, this, value);
  }

  public float getConductance() {
    return daocJNI.HierScore_conductance_get(swigCPtr, this);
  }

  public void setNodesLinks(java.math.BigInteger value) {
    daocJNI.HierScore_nodesLinks_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getNodesLinks() {
    return daocJNI.HierScore_nodesLinks_get(swigCPtr, this);
  }

  public void setClusters(java.math.BigInteger value) {
    daocJNI.HierScore_clusters_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getClusters() {
    return daocJNI.HierScore_clusters_get(swigCPtr, this);
  }

  public HierScore() {
    this(daocJNI.new_HierScore(), true);
  }

}
