/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package info.exascale.daoc;

public class Ids extends java.util.AbstractList<Long> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Ids(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Ids obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        daocJNI.delete_Ids(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Ids(long[] initialElements) {
    this();
    for (long element : initialElements) {
      add(element);
    }
  }

  public Ids(Iterable<Long> initialElements) {
    this();
    for (long element : initialElements) {
      add(element);
    }
  }

  public Long get(int index) {
    return doGet(index);
  }

  public Long set(int index, Long e) {
    return doSet(index, e);
  }

  public boolean add(Long e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Long e) {
    modCount++;
    doAdd(index, e);
  }

  public Long remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public Ids() {
    this(daocJNI.new_Ids__SWIG_0(), true);
  }

  public Ids(Ids other) {
    this(daocJNI.new_Ids__SWIG_1(Ids.getCPtr(other), other), true);
  }

  public long capacity() {
    return daocJNI.Ids_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    daocJNI.Ids_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return daocJNI.Ids_isEmpty(swigCPtr, this);
  }

  public void clear() {
    daocJNI.Ids_clear(swigCPtr, this);
  }

  public Ids(int count) {
    this(daocJNI.new_Ids__SWIG_2(count), true);
  }

  public Ids(int count, long value) {
    this(daocJNI.new_Ids__SWIG_3(count, value), true);
  }

  private int doSize() {
    return daocJNI.Ids_doSize(swigCPtr, this);
  }

  private void doAdd(long value) {
    daocJNI.Ids_doAdd__SWIG_0(swigCPtr, this, value);
  }

  private void doAdd(int index, long value) {
    daocJNI.Ids_doAdd__SWIG_1(swigCPtr, this, index, value);
  }

  private long doRemove(int index) {
    return daocJNI.Ids_doRemove(swigCPtr, this, index);
  }

  private long doGet(int index) {
    return daocJNI.Ids_doGet(swigCPtr, this, index);
  }

  private long doSet(int index, long value) {
    return daocJNI.Ids_doSet(swigCPtr, this, index, value);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    daocJNI.Ids_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
