/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package info.exascale.daoc;

public class InpLink {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected InpLink(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InpLink obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        daocJNI.delete_InpLink(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(long value) {
    daocJNI.InpLink_id_set(swigCPtr, this, value);
  }

  public long getId() {
    return daocJNI.InpLink_id_get(swigCPtr, this);
  }

  public InpLink(long lid) {
    this(daocJNI.new_InpLink__SWIG_0(lid), true);
  }

  public InpLink() {
    this(daocJNI.new_InpLink__SWIG_1(), true);
  }

  public final static boolean IS_WEIGHTED = daocJNI.InpLink_IS_WEIGHTED_get();
  public final static float weight = daocJNI.InpLink_weight_get();
}
