/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package info.exascale.daoc;

public class InpLinks extends java.util.AbstractList<SWIGTYPE_p_daoc__InpLinkT_true_t> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected InpLinks(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InpLinks obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        daocJNI.delete_InpLinks(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public InpLinks(SWIGTYPE_p_daoc__InpLinkT_true_t[] initialElements) {
    this();
    for (SWIGTYPE_p_daoc__InpLinkT_true_t element : initialElements) {
      add(element);
    }
  }

  public InpLinks(Iterable<SWIGTYPE_p_daoc__InpLinkT_true_t> initialElements) {
    this();
    for (SWIGTYPE_p_daoc__InpLinkT_true_t element : initialElements) {
      add(element);
    }
  }

  public SWIGTYPE_p_daoc__InpLinkT_true_t get(int index) {
    return doGet(index);
  }

  public SWIGTYPE_p_daoc__InpLinkT_true_t set(int index, SWIGTYPE_p_daoc__InpLinkT_true_t e) {
    return doSet(index, e);
  }

  public boolean add(SWIGTYPE_p_daoc__InpLinkT_true_t e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, SWIGTYPE_p_daoc__InpLinkT_true_t e) {
    modCount++;
    doAdd(index, e);
  }

  public SWIGTYPE_p_daoc__InpLinkT_true_t remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public InpLinks() {
    this(daocJNI.new_InpLinks__SWIG_0(), true);
  }

  public InpLinks(SWIGTYPE_p_std__vectorT_daoc__InpLinkT_true_t_t other) {
    this(daocJNI.new_InpLinks__SWIG_1(SWIGTYPE_p_std__vectorT_daoc__InpLinkT_true_t_t.getCPtr(other)), true);
  }

  public long capacity() {
    return daocJNI.InpLinks_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    daocJNI.InpLinks_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return daocJNI.InpLinks_isEmpty(swigCPtr, this);
  }

  public void clear() {
    daocJNI.InpLinks_clear(swigCPtr, this);
  }

  public InpLinks(int count) {
    this(daocJNI.new_InpLinks__SWIG_2(count), true);
  }

  public InpLinks(int count, SWIGTYPE_p_daoc__InpLinkT_true_t value) {
    this(daocJNI.new_InpLinks__SWIG_3(count, SWIGTYPE_p_daoc__InpLinkT_true_t.getCPtr(value)), true);
  }

  private int doSize() {
    return daocJNI.InpLinks_doSize(swigCPtr, this);
  }

  private void doAdd(SWIGTYPE_p_daoc__InpLinkT_true_t value) {
    daocJNI.InpLinks_doAdd__SWIG_0(swigCPtr, this, SWIGTYPE_p_daoc__InpLinkT_true_t.getCPtr(value));
  }

  private void doAdd(int index, SWIGTYPE_p_daoc__InpLinkT_true_t value) {
    daocJNI.InpLinks_doAdd__SWIG_1(swigCPtr, this, index, SWIGTYPE_p_daoc__InpLinkT_true_t.getCPtr(value));
  }

  private SWIGTYPE_p_daoc__InpLinkT_true_t doRemove(int index) {
    return new SWIGTYPE_p_daoc__InpLinkT_true_t(daocJNI.InpLinks_doRemove(swigCPtr, this, index), true);
  }

  private SWIGTYPE_p_daoc__InpLinkT_true_t doGet(int index) {
    return new SWIGTYPE_p_daoc__InpLinkT_true_t(daocJNI.InpLinks_doGet(swigCPtr, this, index), false);
  }

  private SWIGTYPE_p_daoc__InpLinkT_true_t doSet(int index, SWIGTYPE_p_daoc__InpLinkT_true_t value) {
    return new SWIGTYPE_p_daoc__InpLinkT_true_t(daocJNI.InpLinks_doSet(swigCPtr, this, index, SWIGTYPE_p_daoc__InpLinkT_true_t.getCPtr(value)), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    daocJNI.InpLinks_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
