/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package info.exascale.daoc;

public class Intrinsics {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Intrinsics(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Intrinsics obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        daocJNI.delete_Intrinsics(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCdn(float value) {
    daocJNI.Intrinsics_cdn_set(swigCPtr, this, value);
  }

  public float getCdn() {
    return daocJNI.Intrinsics_cdn_get(swigCPtr, this);
  }

  public void setMod(float value) {
    daocJNI.Intrinsics_mod_set(swigCPtr, this, value);
  }

  public float getMod() {
    return daocJNI.Intrinsics_mod_get(swigCPtr, this);
  }

  public void setGamma(float value) {
    daocJNI.Intrinsics_gamma_set(swigCPtr, this, value);
  }

  public float getGamma() {
    return daocJNI.Intrinsics_gamma_get(swigCPtr, this);
  }

  public void setSgmod(float value) {
    daocJNI.Intrinsics_sgmod_set(swigCPtr, this, value);
  }

  public float getSgmod() {
    return daocJNI.Intrinsics_sgmod_get(swigCPtr, this);
  }

  public void setFlags(SWIGTYPE_p_IntrinsicsFlags value) {
    daocJNI.Intrinsics_flags_set(swigCPtr, this, SWIGTYPE_p_IntrinsicsFlags.getCPtr(value));
  }

  public SWIGTYPE_p_IntrinsicsFlags getFlags() {
    return new SWIGTYPE_p_IntrinsicsFlags(daocJNI.Intrinsics_flags_get(swigCPtr, this), true);
  }

  public Intrinsics() {
    this(daocJNI.new_Intrinsics(), true);
  }

  public boolean defined() {
    return daocJNI.Intrinsics_defined(swigCPtr, this);
  }

}
