/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package info.exascale.daoc;

public class LinkSrcDstId {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected LinkSrcDstId(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LinkSrcDstId obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        daocJNI.delete_LinkSrcDstId(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSid(long value) {
    daocJNI.LinkSrcDstId_sid_set(swigCPtr, this, value);
  }

  public long getSid() {
    return daocJNI.LinkSrcDstId_sid_get(swigCPtr, this);
  }

  public void setDid(long value) {
    daocJNI.LinkSrcDstId_did_set(swigCPtr, this, value);
  }

  public long getDid() {
    return daocJNI.LinkSrcDstId_did_get(swigCPtr, this);
  }

  public LinkSrcDstId(long src, long dst) {
    this(daocJNI.new_LinkSrcDstId__SWIG_0(src, dst), true);
  }

  public LinkSrcDstId(long src) {
    this(daocJNI.new_LinkSrcDstId__SWIG_1(src), true);
  }

  public LinkSrcDstId() {
    this(daocJNI.new_LinkSrcDstId__SWIG_2(), true);
  }

}
