/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package info.exascale.daoc;

public class Node {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Node(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Node obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        daocJNI.delete_Node(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public long getId() {
    return daocJNI.Node_id_get(swigCPtr, this);
  }

  public SWIGTYPE_p_daoc__OwnersT_daoc__NodeT_std__vectorT_daoc__WeightedLinkT_float_t_t_t__NodeIT__links_type_t owncs() {
    return new SWIGTYPE_p_daoc__OwnersT_daoc__NodeT_std__vectorT_daoc__WeightedLinkT_float_t_t_t__NodeIT__links_type_t(daocJNI.Node_owncs(swigCPtr, this), false);
  }

  public void setLinks(SWIGTYPE_p_std__vectorT_daoc__WeightedLinkT_float_t_t value) {
    daocJNI.Node_links_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_daoc__WeightedLinkT_float_t_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_daoc__WeightedLinkT_float_t_t getLinks() {
    long cPtr = daocJNI.Node_links_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_daoc__WeightedLinkT_float_t_t(cPtr, false);
  }

  public Node(long nid, java.math.BigInteger linksNum) {
    this(daocJNI.new_Node__SWIG_0(nid, linksNum), true);
  }

  public Node(long nid) {
    this(daocJNI.new_Node__SWIG_1(nid), true);
  }

  public Node(Node arg0) {
    this(daocJNI.new_Node__SWIG_2(Node.getCPtr(arg0), arg0), true);
  }

  public double weight() {
    return daocJNI.Node_weight(swigCPtr, this);
  }

  public void addWeight(double weight) {
    daocJNI.Node_addWeight(swigCPtr, this, weight);
  }

  public double ctxWeight() {
    return daocJNI.Node_ctxWeight(swigCPtr, this);
  }

  public SWIGTYPE_p_daoc__ItemsT_daoc__NodeIT_std__vectorT_daoc__WeightedLinkT_float_t_t_t_p_t descs() {
    long cPtr = daocJNI.Node_descs(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_daoc__ItemsT_daoc__NodeIT_std__vectorT_daoc__WeightedLinkT_float_t_t_t_p_t(cPtr, false);
  }

  public void tidy() {
    daocJNI.Node_tidy(swigCPtr, this);
  }

}
