/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package info.exascale.daoc;

public class NodeShare {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NodeShare(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NodeShare obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        daocJNI.delete_NodeShare(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDest(SWIGTYPE_p_std__vectorT_daoc__WeightedLinkT_float_t_t value) {
    daocJNI.NodeShare_dest_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_daoc__WeightedLinkT_float_t_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_daoc__WeightedLinkT_float_t_t getDest() {
    long cPtr = daocJNI.NodeShare_dest_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_daoc__WeightedLinkT_float_t_t(cPtr, false);
  }

  public void setShare(float value) {
    daocJNI.NodeShare_share_set(swigCPtr, this, value);
  }

  public float getShare() {
    return daocJNI.NodeShare_share_get(swigCPtr, this);
  }

  public NodeShare(SWIGTYPE_p_std__vectorT_daoc__WeightedLinkT_float_t_t adest, float ashare) {
    this(daocJNI.new_NodeShare__SWIG_0(SWIGTYPE_p_std__vectorT_daoc__WeightedLinkT_float_t_t.getCPtr(adest), ashare), true);
  }

  public NodeShare(SWIGTYPE_p_std__vectorT_daoc__WeightedLinkT_float_t_t adest) {
    this(daocJNI.new_NodeShare__SWIG_1(SWIGTYPE_p_std__vectorT_daoc__WeightedLinkT_float_t_t.getCPtr(adest)), true);
  }

  public NodeShare(NodeShare arg0) {
    this(daocJNI.new_NodeShare__SWIG_2(NodeShare.getCPtr(arg0), arg0), true);
  }

  public NodeShare assign(NodeShare arg0) {
    return new NodeShare(daocJNI.NodeShare_assign(swigCPtr, this, NodeShare.getCPtr(arg0), arg0), false);
  }

}
