/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package info.exascale.daoc;

public class NslParser {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NslParser(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NslParser obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        daocJNI.delete_NslParser(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public NslParser(SWIGTYPE_p_InpOptions inpopts) {
    this(daocJNI.new_NslParser(SWIGTYPE_p_InpOptions.getCPtr(inpopts)), true);
  }

  public boolean weighted() {
    return daocJNI.NslParser_weighted(swigCPtr, this);
  }

  public SGraphPtr sbuild() {
    return new SGraphPtr(daocJNI.NslParser_sbuild(swigCPtr, this), true);
  }

  public GraphPtr build() {
    return new GraphPtr(daocJNI.NslParser_build(swigCPtr, this), true);
  }

}
