/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package info.exascale.daoc;

public class OutputOptions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OutputOptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OutputOptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        daocJNI.delete_OutputOptions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setClsfmt(SWIGTYPE_p_ClsOutFmt value) {
    daocJNI.OutputOptions_clsfmt_set(swigCPtr, this, SWIGTYPE_p_ClsOutFmt.getCPtr(value));
  }

  public SWIGTYPE_p_ClsOutFmt getClsfmt() {
    return new SWIGTYPE_p_ClsOutFmt(daocJNI.OutputOptions_clsfmt_get(swigCPtr, this), true);
  }

  public void setEstcls(long value) {
    daocJNI.OutputOptions_estcls_set(swigCPtr, this, value);
  }

  public long getEstcls() {
    return daocJNI.OutputOptions_estcls_get(swigCPtr, this);
  }

  public void setEstclsMax(long value) {
    daocJNI.OutputOptions_estclsMax_set(swigCPtr, this, value);
  }

  public long getEstclsMax() {
    return daocJNI.OutputOptions_estclsMax_get(swigCPtr, this);
  }

  public void setClsrstep(float value) {
    daocJNI.OutputOptions_clsrstep_set(swigCPtr, this, value);
  }

  public float getClsrstep() {
    return daocJNI.OutputOptions_clsrstep_get(swigCPtr, this);
  }

  public void setClsfile(SWIGTYPE_p_string value) {
    daocJNI.OutputOptions_clsfile_set(swigCPtr, this, SWIGTYPE_p_string.getCPtr(value));
  }

  public SWIGTYPE_p_string getClsfile() {
    return new SWIGTYPE_p_string(daocJNI.OutputOptions_clsfile_get(swigCPtr, this), true);
  }

  public void setFltMembers(boolean value) {
    daocJNI.OutputOptions_fltMembers_set(swigCPtr, this, value);
  }

  public boolean getFltMembers() {
    return daocJNI.OutputOptions_fltMembers_get(swigCPtr, this);
  }

  public OutputOptions() {
    this(daocJNI.new_OutputOptions(), true);
  }

}
