/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package info.exascale.daoc;

public class Owner {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Owner(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Owner obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        daocJNI.delete_Owner(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDest(Cluster value) {
    daocJNI.Owner_dest_set(swigCPtr, this, Cluster.getCPtr(value), value);
  }

  public Cluster getDest() {
    long cPtr = daocJNI.Owner_dest_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Cluster(cPtr, false);
  }

  public void setNumac(int value) {
    daocJNI.Owner_numac_set(swigCPtr, this, value);
  }

  public int getNumac() {
    return daocJNI.Owner_numac_get(swigCPtr, this);
  }

  public Owner(Cluster cl, long numacands) {
    this(daocJNI.new_Owner__SWIG_0(Cluster.getCPtr(cl), cl, numacands), true);
  }

  public Owner(Cluster cl) {
    this(daocJNI.new_Owner__SWIG_1(Cluster.getCPtr(cl), cl), true);
  }

  public Owner(Owner arg0) {
    this(daocJNI.new_Owner__SWIG_2(Owner.getCPtr(arg0), arg0), true);
  }

  public Owner assign(Owner arg0) {
    return new Owner(daocJNI.Owner_assign(swigCPtr, this, Owner.getCPtr(arg0), arg0), false);
  }

  public boolean equal(Owner ow) {
    return daocJNI.Owner_equal__SWIG_0(swigCPtr, this, Owner.getCPtr(ow), ow);
  }

  public boolean unequal(Owner ow) {
    return daocJNI.Owner_unequal__SWIG_0(swigCPtr, this, Owner.getCPtr(ow), ow);
  }

  public boolean equal(Cluster oc) {
    return daocJNI.Owner_equal__SWIG_1(swigCPtr, this, Cluster.getCPtr(oc), oc);
  }

  public boolean unequal(Cluster oc) {
    return daocJNI.Owner_unequal__SWIG_1(swigCPtr, this, Cluster.getCPtr(oc), oc);
  }

}
