/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package info.exascale.daoc;

public class RawMembership {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RawMembership(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RawMembership obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        daocJNI.delete_RawMembership(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIGTYPE_p_daoc__ClustersT_std__vectorT_daoc__WeightedLinkT_float_t_t_t getClusters() {
    long cPtr = daocJNI.RawMembership_clusters_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_daoc__ClustersT_std__vectorT_daoc__WeightedLinkT_float_t_t_t(cPtr, false);
  }

  public void setNdshares(SWIGTYPE_p_daoc__NodesSharesT_std__vectorT_daoc__WeightedLinkT_float_t_t_t value) {
    daocJNI.RawMembership_ndshares_set(swigCPtr, this, SWIGTYPE_p_daoc__NodesSharesT_std__vectorT_daoc__WeightedLinkT_float_t_t_t.getCPtr(value));
  }

  public SWIGTYPE_p_daoc__NodesSharesT_std__vectorT_daoc__WeightedLinkT_float_t_t_t getNdshares() {
    long cPtr = daocJNI.RawMembership_ndshares_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_daoc__NodesSharesT_std__vectorT_daoc__WeightedLinkT_float_t_t_t(cPtr, false);
  }

  public RawMembership() {
    this(daocJNI.new_RawMembership__SWIG_0(), true);
  }

  public RawMembership(RawMembership arg0) {
    this(daocJNI.new_RawMembership__SWIG_1(RawMembership.getCPtr(arg0), arg0), true);
  }

  public RawMembership assign(RawMembership arg0) {
    return new RawMembership(daocJNI.RawMembership_assign(swigCPtr, this, RawMembership.getCPtr(arg0), arg0), false);
  }

}
