/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package info.exascale.daoc;

public class RcgParser {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RcgParser(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RcgParser obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        daocJNI.delete_RcgParser(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RcgParser(SWIGTYPE_p_InpOptions inpopts) {
    this(daocJNI.new_RcgParser(SWIGTYPE_p_InpOptions.getCPtr(inpopts)), true);
  }

  public boolean weighted() {
    return daocJNI.RcgParser_weighted(swigCPtr, this);
  }

  public boolean validated() {
    return daocJNI.RcgParser_validated(swigCPtr, this);
  }

  public SGraphPtr sbuild() {
    return new SGraphPtr(daocJNI.RcgParser_sbuild(swigCPtr, this), true);
  }

  public GraphPtr build() {
    return new GraphPtr(daocJNI.RcgParser_build(swigCPtr, this), true);
  }

}
