/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package info.exascale.daoc;

public class RhbPrinter {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RhbPrinter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RhbPrinter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        daocJNI.delete_RhbPrinter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RhbPrinter(SWIGTYPE_p_shared_ptrT_daoc__HierarchyT_std__vectorT_daoc__WeightedLinkT_float_t_t_t_t hier) {
    this(daocJNI.new_RhbPrinter(SWIGTYPE_p_shared_ptrT_daoc__HierarchyT_std__vectorT_daoc__WeightedLinkT_float_t_t_t_t.getCPtr(hier)), true);
  }

  public void output(SWIGTYPE_p_FileWrapper fout) {
    daocJNI.RhbPrinter_output(swigCPtr, this, SWIGTYPE_p_FileWrapper.getCPtr(fout));
  }

}
