/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package info.exascale.daoc;

public class SCnlPrinter {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SCnlPrinter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SCnlPrinter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        daocJNI.delete_SCnlPrinter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SCnlPrinter(SWIGTYPE_p_shared_ptrT_daoc__HierarchyT_std__vectorT_daoc__SimpleLinkT_float_t_t_t_t hier) {
    this(daocJNI.new_SCnlPrinter(SWIGTYPE_p_shared_ptrT_daoc__HierarchyT_std__vectorT_daoc__SimpleLinkT_float_t_t_t_t.getCPtr(hier)), true);
  }

  public void output(SWIGTYPE_p_FileWrappers fouts, SWIGTYPE_p_ClsOutFmt clsfmt, boolean fltMembers, long blev, long elev, float levStepRatio) {
    daocJNI.SCnlPrinter_output__SWIG_0(swigCPtr, this, SWIGTYPE_p_FileWrappers.getCPtr(fouts), SWIGTYPE_p_ClsOutFmt.getCPtr(clsfmt), fltMembers, blev, elev, levStepRatio);
  }

  public void output(SWIGTYPE_p_FileWrappers fouts, SWIGTYPE_p_ClsOutFmt clsfmt, boolean fltMembers, long blev, long elev) {
    daocJNI.SCnlPrinter_output__SWIG_1(swigCPtr, this, SWIGTYPE_p_FileWrappers.getCPtr(fouts), SWIGTYPE_p_ClsOutFmt.getCPtr(clsfmt), fltMembers, blev, elev);
  }

  public void output(SWIGTYPE_p_FileWrappers fouts, SWIGTYPE_p_ClsOutFmt clsfmt, boolean fltMembers, long blev) {
    daocJNI.SCnlPrinter_output__SWIG_2(swigCPtr, this, SWIGTYPE_p_FileWrappers.getCPtr(fouts), SWIGTYPE_p_ClsOutFmt.getCPtr(clsfmt), fltMembers, blev);
  }

  public void output(SWIGTYPE_p_FileWrappers fouts, SWIGTYPE_p_ClsOutFmt clsfmt, boolean fltMembers) {
    daocJNI.SCnlPrinter_output__SWIG_3(swigCPtr, this, SWIGTYPE_p_FileWrappers.getCPtr(fouts), SWIGTYPE_p_ClsOutFmt.getCPtr(clsfmt), fltMembers);
  }

  public void output(SWIGTYPE_p_FileWrappers fouts, SWIGTYPE_p_ClsOutFmt clsfmt) {
    daocJNI.SCnlPrinter_output__SWIG_4(swigCPtr, this, SWIGTYPE_p_FileWrappers.getCPtr(fouts), SWIGTYPE_p_ClsOutFmt.getCPtr(clsfmt));
  }

}
