/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package info.exascale.daoc;

public class SInpLinks extends java.util.AbstractList<InpLink> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SInpLinks(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SInpLinks obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        daocJNI.delete_SInpLinks(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SInpLinks(InpLink[] initialElements) {
    this();
    for (InpLink element : initialElements) {
      add(element);
    }
  }

  public SInpLinks(Iterable<InpLink> initialElements) {
    this();
    for (InpLink element : initialElements) {
      add(element);
    }
  }

  public InpLink get(int index) {
    return doGet(index);
  }

  public InpLink set(int index, InpLink e) {
    return doSet(index, e);
  }

  public boolean add(InpLink e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, InpLink e) {
    modCount++;
    doAdd(index, e);
  }

  public InpLink remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public SInpLinks() {
    this(daocJNI.new_SInpLinks__SWIG_0(), true);
  }

  public SInpLinks(SInpLinks other) {
    this(daocJNI.new_SInpLinks__SWIG_1(SInpLinks.getCPtr(other), other), true);
  }

  public long capacity() {
    return daocJNI.SInpLinks_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    daocJNI.SInpLinks_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return daocJNI.SInpLinks_isEmpty(swigCPtr, this);
  }

  public void clear() {
    daocJNI.SInpLinks_clear(swigCPtr, this);
  }

  public SInpLinks(int count) {
    this(daocJNI.new_SInpLinks__SWIG_2(count), true);
  }

  public SInpLinks(int count, InpLink value) {
    this(daocJNI.new_SInpLinks__SWIG_3(count, InpLink.getCPtr(value), value), true);
  }

  private int doSize() {
    return daocJNI.SInpLinks_doSize(swigCPtr, this);
  }

  private void doAdd(InpLink value) {
    daocJNI.SInpLinks_doAdd__SWIG_0(swigCPtr, this, InpLink.getCPtr(value), value);
  }

  private void doAdd(int index, InpLink value) {
    daocJNI.SInpLinks_doAdd__SWIG_1(swigCPtr, this, index, InpLink.getCPtr(value), value);
  }

  private InpLink doRemove(int index) {
    return new InpLink(daocJNI.SInpLinks_doRemove(swigCPtr, this, index), true);
  }

  private InpLink doGet(int index) {
    return new InpLink(daocJNI.SInpLinks_doGet(swigCPtr, this, index), false);
  }

  private InpLink doSet(int index, InpLink value) {
    return new InpLink(daocJNI.SInpLinks_doSet(swigCPtr, this, index, InpLink.getCPtr(value), value), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    daocJNI.SInpLinks_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
