/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package info.exascale.daoc;

public class SItem {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SItem(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SItem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        daocJNI.delete_SItem(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public long getId() {
    return daocJNI.SItem_id_get(swigCPtr, this);
  }

  public void setTotac(long value) {
    daocJNI.SItem_totac_set(swigCPtr, this, value);
  }

  public long getTotac() {
    return daocJNI.SItem_totac_get(swigCPtr, this);
  }

  public SWIGTYPE_p_daoc__OwnersT_std__vectorT_daoc__SimpleLinkT_float_t_t_t owncs() {
    return new SWIGTYPE_p_daoc__OwnersT_std__vectorT_daoc__SimpleLinkT_float_t_t_t(daocJNI.SItem_owncs(swigCPtr, this), false);
  }

  public double weight() {
    return daocJNI.SItem_weight(swigCPtr, this);
  }

  public void addWeight(double weight) {
    daocJNI.SItem_addWeight(swigCPtr, this, weight);
  }

  public double ctxWeight() {
    return daocJNI.SItem_ctxWeight(swigCPtr, this);
  }

  public SWIGTYPE_p_daoc__ItemsT_daoc__NodeIT_daoc__LinksT_daoc__SimpleLinkT_daoc__LinkWeight_t_t_t_p_t descs() {
    long cPtr = daocJNI.SItem_descs(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_daoc__ItemsT_daoc__NodeIT_daoc__LinksT_daoc__SimpleLinkT_daoc__LinkWeight_t_t_t_p_t(cPtr, false);
  }

  public void tidy() {
    daocJNI.SItem_tidy(swigCPtr, this);
  }

}
