/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package info.exascale.daoc;

public class SLevel {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SLevel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SLevel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        daocJNI.delete_SLevel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFullsize(long value) {
    daocJNI.SLevel_fullsize_set(swigCPtr, this, value);
  }

  public long getFullsize() {
    return daocJNI.SLevel_fullsize_get(swigCPtr, this);
  }

  public SWIGTYPE_p_daoc__ClustersT_std__vectorT_daoc__SimpleLinkT_float_t_t_t items() {
    return new SWIGTYPE_p_daoc__ClustersT_std__vectorT_daoc__SimpleLinkT_float_t_t_t(daocJNI.SLevel_items(swigCPtr, this), false);
  }

  public SLevel(long size) {
    this(daocJNI.new_SLevel__SWIG_0(size), true);
  }

  public SLevel(long size, SWIGTYPE_p_daoc__ClustersT_std__vectorT_daoc__SimpleLinkT_float_t_t_t cls) {
    this(daocJNI.new_SLevel__SWIG_1(size, SWIGTYPE_p_daoc__ClustersT_std__vectorT_daoc__SimpleLinkT_float_t_t_t.getCPtr(cls)), true);
  }

  public SLevel(SLevel arg0) {
    this(daocJNI.new_SLevel__SWIG_2(SLevel.getCPtr(arg0), arg0), true);
  }

  public SLevel assign(SLevel arg0) {
    return new SLevel(daocJNI.SLevel_assign(swigCPtr, this, SLevel.getCPtr(arg0), arg0), false);
  }

}
