/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package info.exascale.daoc;

public class SNodeShare {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SNodeShare(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SNodeShare obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        daocJNI.delete_SNodeShare(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDest(SWIGTYPE_p_std__vectorT_daoc__SimpleLinkT_float_t_t value) {
    daocJNI.SNodeShare_dest_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_daoc__SimpleLinkT_float_t_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_daoc__SimpleLinkT_float_t_t getDest() {
    long cPtr = daocJNI.SNodeShare_dest_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_daoc__SimpleLinkT_float_t_t(cPtr, false);
  }

  public void setShare(float value) {
    daocJNI.SNodeShare_share_set(swigCPtr, this, value);
  }

  public float getShare() {
    return daocJNI.SNodeShare_share_get(swigCPtr, this);
  }

  public SNodeShare(SWIGTYPE_p_std__vectorT_daoc__SimpleLinkT_float_t_t adest, float ashare) {
    this(daocJNI.new_SNodeShare__SWIG_0(SWIGTYPE_p_std__vectorT_daoc__SimpleLinkT_float_t_t.getCPtr(adest), ashare), true);
  }

  public SNodeShare(SWIGTYPE_p_std__vectorT_daoc__SimpleLinkT_float_t_t adest) {
    this(daocJNI.new_SNodeShare__SWIG_1(SWIGTYPE_p_std__vectorT_daoc__SimpleLinkT_float_t_t.getCPtr(adest)), true);
  }

  public SNodeShare(SNodeShare arg0) {
    this(daocJNI.new_SNodeShare__SWIG_2(SNodeShare.getCPtr(arg0), arg0), true);
  }

  public SNodeShare assign(SNodeShare arg0) {
    return new SNodeShare(daocJNI.SNodeShare_assign(swigCPtr, this, SNodeShare.getCPtr(arg0), arg0), false);
  }

}
