/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package info.exascale.daoc;

public class SOwner {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SOwner(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SOwner obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        daocJNI.delete_SOwner(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDest(SCluster value) {
    daocJNI.SOwner_dest_set(swigCPtr, this, SCluster.getCPtr(value), value);
  }

  public SCluster getDest() {
    long cPtr = daocJNI.SOwner_dest_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SCluster(cPtr, false);
  }

  public void setNumac(int value) {
    daocJNI.SOwner_numac_set(swigCPtr, this, value);
  }

  public int getNumac() {
    return daocJNI.SOwner_numac_get(swigCPtr, this);
  }

  public SOwner(SCluster cl, long numacands) {
    this(daocJNI.new_SOwner__SWIG_0(SCluster.getCPtr(cl), cl, numacands), true);
  }

  public SOwner(SCluster cl) {
    this(daocJNI.new_SOwner__SWIG_1(SCluster.getCPtr(cl), cl), true);
  }

  public SOwner(SOwner arg0) {
    this(daocJNI.new_SOwner__SWIG_2(SOwner.getCPtr(arg0), arg0), true);
  }

  public SOwner assign(SOwner arg0) {
    return new SOwner(daocJNI.SOwner_assign(swigCPtr, this, SOwner.getCPtr(arg0), arg0), false);
  }

  public boolean equal(SOwner ow) {
    return daocJNI.SOwner_equal__SWIG_0(swigCPtr, this, SOwner.getCPtr(ow), ow);
  }

  public boolean unequal(SOwner ow) {
    return daocJNI.SOwner_unequal__SWIG_0(swigCPtr, this, SOwner.getCPtr(ow), ow);
  }

  public boolean equal(SCluster oc) {
    return daocJNI.SOwner_equal__SWIG_1(swigCPtr, this, SCluster.getCPtr(oc), oc);
  }

  public boolean unequal(SCluster oc) {
    return daocJNI.SOwner_unequal__SWIG_1(swigCPtr, this, SCluster.getCPtr(oc), oc);
  }

}
