/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package info.exascale.daoc;

public class StructErrors {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StructErrors(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StructErrors obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        daocJNI.delete_StructErrors(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMessage(String value) {
    daocJNI.StructErrors_message_set(swigCPtr, this, value);
  }

  public String getMessage() {
    return daocJNI.StructErrors_message_get(swigCPtr, this);
  }

  public void setSize(java.math.BigInteger value) {
    daocJNI.StructErrors_size_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getSize() {
    return daocJNI.StructErrors_size_get(swigCPtr, this);
  }

  public StructErrors assign(StructErrors arg0) {
    return new StructErrors(daocJNI.StructErrors_assign(swigCPtr, this, StructErrors.getCPtr(arg0), arg0), false);
  }

  public void show() {
    daocJNI.StructErrors_show(swigCPtr, this);
  }

  public boolean defined() {
    return daocJNI.StructErrors_defined(swigCPtr, this);
  }

  public final static long ERRORS_MAX = daocJNI.StructErrors_ERRORS_MAX_get();
}
