/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package info.exascale.daoc;

public class StructLinkErrors extends StructErrors {
  private transient long swigCPtr;

  protected StructLinkErrors(long cPtr, boolean cMemoryOwn) {
    super(daocJNI.StructLinkErrors_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StructLinkErrors obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        daocJNI.delete_StructLinkErrors(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setLids(LinkSrcDstId value) {
    daocJNI.StructLinkErrors_lids_set(swigCPtr, this, LinkSrcDstId.getCPtr(value), value);
  }

  public LinkSrcDstId getLids() {
    long cPtr = daocJNI.StructLinkErrors_lids_get(swigCPtr, this);
    return (cPtr == 0) ? null : new LinkSrcDstId(cPtr, false);
  }

  public StructLinkErrors(String msg) {
    this(daocJNI.new_StructLinkErrors(msg), true);
  }

  public void add(LinkSrcDstId lid) {
    daocJNI.StructLinkErrors_add(swigCPtr, this, LinkSrcDstId.getCPtr(lid), lid);
  }

}
