/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package info.exascale.daoc;

public class SWIGTYPE_p_daoc__ItemsT_daoc__NodeIT_std__vectorT_daoc__SimpleLinkT_float_t_t_t_p_t {
  private transient long swigCPtr;

  protected SWIGTYPE_p_daoc__ItemsT_daoc__NodeIT_std__vectorT_daoc__SimpleLinkT_float_t_t_t_p_t(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_daoc__ItemsT_daoc__NodeIT_std__vectorT_daoc__SimpleLinkT_float_t_t_t_p_t() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_daoc__ItemsT_daoc__NodeIT_std__vectorT_daoc__SimpleLinkT_float_t_t_t_p_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

